name: microservices-dev

services:
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: microservices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
