extend type Query {
    products: [Product]! @isAuthenticated
}

extend type Mutation {
    createProduct(input: CreateProductInput!): Boolean! @isAuthenticated
    updateProduct(id: UUID!, input: UpdateProductInput!): Boolean! @isAuthenticated
    deleteProduct(id: UUID!): Boolean! @isAuthenticated
}

type Product {
    id: UUID!
    title: String!
    description: String
    createdAt: Time!
}

input CreateProductInput {
    title: String!
    description: String
}

input UpdateProductInput {
    title: String
    description: String
}
