// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodel

import (
	"time"

	"github.com/google/uuid"
)

type CreateProductInput struct {
	Title string `json:"title"`
}

type Mutation struct {
}

type Product struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"createdAt"`
}

type Query struct {
}

type UpdateProductInput struct {
	Title string `json:"title"`
}
