http:
  address: 0.0.0.0:8000
grpc:
  client:
    user:
      address: user:50050
    product:
      address: product:50051
    auth:
      address: auth:50054
jwt:
  secret: asfsf90s8f0s8f0sd8fsfklsjfsdof8uqewrnmnaldf
